feature: Change createSpending contoller
anastasiya-nd/budget-app pull request #19
Opened 2021-10-14 19:28 UTC by anastasiya-nd

2021-10-15 08:18 UTC, ok2ju requested changes

2021-10-15 08:18 UTC, ok2ju commented on src/models/Spending.js
> +    enum: ['Shopping', 'Entertainment', 'Car', 'Bills', 'Food', 'Home', 'Education', 'Other'],
at the database it's better to store values in lowercase

2021-10-16 09:09 UTC, anastasiya-nd commented on src/models/Spending.js
> +    enum: ['Shopping', 'Entertainment', 'Car', 'Bills', 'Food', 'Home', 'Education', 'Other'],
I have done

2021-10-16 10:50 UTC, ok2ju approved these changes

2021-10-16 10:50 UTC, merged